### ISSUE TITLE
Good guy

### ISSUE THREAD

**Issue by Joyace** [akiirui/play-with-mpv-handler#1]
Good guy, look forward to Windows

**Comment by akiirui** [comment]
At https://github.com/akiirui/play-with-mpv-handler/commit/7965ab264f17630cff17878825b4510ad4146158, [`mpv-handler`](https://github.com/akiirui/play-with-mpv-handler/blob/main/windows/mpv-handler.bat) already supports Windows. 🎉🎉🎉

**Comment by Joyace** [comment]
![QQ截图20201119154334.png](https://i.loli.net/2020/11/19/JmwcheptyoZuMAF.png)
报错了

**Comment by akiirui** [comment]
@Joyace 是 `handler-install.bat` 报错还是从网页调用的时候报错？

**Comment by Joyace** [comment]
@akiirui 调用的时候报错

**Comment by akiirui** [comment]
@Joyace 找到原因了。。。我这里测试的时候有把 mpv 的目录加入 PATH。
然后 `mpv-handler.bat` 里漏掉了 `cd /D %~dp0`。
然后执行的时候 PWD 并没有在 mpv 的目录里。

https://github.com/akiirui/play-with-mpv-handler/blob/main/windows/mpv-handler.bat

**Comment by Joyace** [comment]
@akiirui 又遇到新的问题了。。。
![QQ截图20201119154127.png](https://i.loli.net/2020/11/19/e1DiIfSsdCaktnJ.png)

**Comment by akiirui** [comment]
这个是你自己的脚本问题哟，和本项目无关。
你 `script-opts/mpv_thumbnail_script.conf: L32` 配置有误。

**Comment by Joyace** [comment]
用了你推荐的MPV 提示这个
[url=https://sm.ms/image/B8Y52C6kQqdt3yE][img]https://i.loli.net/2020/11/19/B8Y52C6kQqdt3yE.png[/img][/url]

**Comment by akiirui** [comment]
> 用了你推荐的MPV 提示这个
> [url=https://sm.ms/image/B8Y52C6kQqdt3yE][img][https://i.loli.net/2020/11/19/B8Y52C6kQqdt3yE.png[/img][/url]](https://i.loli.net/2020/11/19/B8Y52C6kQqdt3yE.png%5B/img%5D%5B/url%5D)

这个只是一个有多个配置文件目录的警告，可以忽略的。
现在是否可以从网页调用播放视频了？

**Comment by Joyace** [comment]
播放不了，后面闪过了一串红字 然后窗口关闭了，应该还是有问题

**Comment by Joyace** [comment]
截到了
![QQ截图20201119155236.png](https://i.loli.net/2020/11/19/OVZHWilTP79Yhbm.png)

**Comment by akiirui** [comment]
> 截到了
> ![QQ截图20201119155236.png](https://camo.githubusercontent.com/a9d00c6e9ff384dd5f2a372049c3739859e9791193a1ca2dcd4131c682636e32/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31312f31392f4f565a4857696c545037395968626d2e706e67)

这是没有找到 `youtube-dl`，你有运行 `update.bat` 更新 `mpv` 和 `youtube-dl` 么

**Comment by Joyace** [comment]
啊！ 我不知道要放youtube-dl到mpv目录，现在可以用了，非常感谢

**Comment by akiirui** [comment]
可以用了就好~ 第一个没找到 `mpv.com` 的问题是我测试失误。

安装后建议执行 `update.bat` 我也添加到了 README。

感谢反馈问题和测试~
